### ISSUE TITLE
The deployed app doesn't work

### ISSUE THREAD

**Issue by Rajdeepc** [replicate/clipdraw-interactive#3]
I can see the payload going as bus and the returned token is passed to successive get calls to fetch the list of collections.
But every output is null

![Screenshot 2022-11-01 at 12 31 03 AM](https://user-images.githubusercontent.com/8790510/199088637-a0a78dfa-57ab-449c-abaf-f8d79a6a4081.png)

**Comment by Rajdeepc** [comment]
My Bad.. It took almost 5 mins to generate a bus. Closing this

**Comment by zeke** [comment]
Thanks for following up!
